Add ESLinter for JS Linting
bloom-works/guides-template pull request #45
Opened 2023-07-04 15:50 UTC by LynnHerrick9

This changes is related to the [Setup Guides](https://github.com/bloom-works/guides-template/issues/5) task.  It adds linting functionality for JavaScript files.  The linter can be run at any point during development.  It is also added to the workflow process (from PR click checks tab in top-middle of screen, click Pull Request on left side of screen, click pr_checks on left-side or middle of screen, click Run Linter in middle of screen).  Prior to this change the run linter option in PR Check was a print statement as a placeholder. 

To make it more consumable for review, I will split up all the linter work into PRs associated to each linter and language.  This review will include all changes for ESLint and JavaScript code.

### What was changed

- Added ESLint capabilities (packages, configuration)
- Updated sh file used in github workflows for pr check 
- Add steps to run before PR to developer section of README 
- Fixed changes in JS files reported by linter

### How to check change

1. Checkout branch and build project
2. Verify all changes reported by linter did not disrupt the project by running `npm run serve`
3. Verify there are no existing linter errors by using the path on PR above to see if pr checks passed for linter
4. Verify there are no existing linter errors by manually running the linter in the code.  Navigate to the base of the repo and run `sh ./ci/linter.sh`.  Below image shows an example of what the command line will look like when there are no errors.
<img width="311" alt="Screenshot 2023-07-04 at 8 27 28 AM" src="https://github.com/bloom-works/guides-template/assets/137226010/f38ba5e3-4409-46f6-aaff-e0dad41e2631">

6. Verify linter is working and/or check any style fixes I made in other files.  For this you will use the same command as above and choose any of the files that have changed and reverse any changes made.  I have give two examples below, but feel free to check any of the changes using the same process.

Example 1: Here I have changed the single quotes back to double quotes on line 2 of the markdown.js file and then run the linter.  Note the linter now reports an error for _quotes_ with the message that _Strings must use singlequote_.
<img width="576" alt="Screenshot 2023-07-04 at 8 28 41 AM" src="https://github.com/bloom-works/guides-template/assets/137226010/6dbb6fe6-4f62-4248-8eca-acd5739cd616">
 
Example2: Here I have navigated to a different directory from the first example (_includes/components/) and removed the added space on line 4 of the PageHeader.js file.  Note the linter now reports and error for _space-before-function-paren_ with the message _Missing space before function parentheses_.

### Notes

I have turned two rules off within the .eslintrc.js file. 

- semi: By default this will error for any added semicolons at the end of lines.  The semicolon is not required in JS but can be useful to avoid syntax errors when the compiler cannot auto-add.  We have a mixed usage, which _could_ be intentional.  If we ever decide to always use or never use, I have added a note to the configuration on what to change it to.
- no-unused-vars: I believe this is due to not all changes being added to the project yet and we can remove this ignored rule completly once all changes have been merged to main.

2023-07-05 13:32 UTC, jeffmaher requested changes
Added a couple comments and potentially one change requested, but looking really good and thanks for the great PR description and included documentation!

2023-07-05 18:09 UTC, SMakaiTakori commented on .eslintrc.js
> +      files: [
@jeffmaher @LynnHerrick9 I have looked into this and it seems that `eslint` automatically ignores files with a `.` in front of them, such as `.gitignore`, etc. so it seems the fix for this is to explicity add `ignorePatterns` to our `eslint` configurations for specific files like this that we don't want ignored.

I have [found a solution](https://github.com/eslint/eslint/issues/15687) for this and our `.eleventy.js` file now has 63 errors, which I am in the process of fixing. I will push up my code once I have taken care of the errors. 


![eslintConfig](https://github.com/bloom-works/guides-template/assets/20325483/23215e0c-20aa-4d8e-b996-19f029420a04)

2023-07-05 21:00 UTC, SMakaiTakori commented on .eslintrc.js
> +      files: [
I was able to resolve the issue of our eleventy config not being included in the linter process in this PR #48 . All errors have been resolved and the PR can be merged into this one after @jeffmaher and @LynnHerrick9 take a look.

2023-07-06 19:05 UTC, jeffmaher approved these changes

2023-07-06 19:16 UTC, merged